alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
alter table awarded drop foreign key FKisajb610j0y27hp7wpq9kbcvl;
alter table awarded drop foreign key FK3dnnrmx6syuodat89m59phy74;
alter table purchaser drop foreign key FK4khm2bepsctxlc7jyolu03v7i;
alter table type drop foreign key FKn4tpfyjxtilug2cxlgthtvj8r;
drop table if exists awarded;
drop table if exists purchaser;
drop table if exists supplier;
drop table if exists tender;
drop table if exists type;
